management:
  endpoints:
      web:
          exposure:
            include: '*'
      endpoint:
          health:
          show-details: ALWAYS

server:
   port: 12001

spring:
  application:
      name: admin-service
  boot:
      admin:
        client:
          url: http://localhost:12997
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tbms?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT
      username: root
      password: Sgcc@ECP2.0  #tbms 8.210.171.80 mysql passwd
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        filters: stat,wall
        use-global-data-source-stat: true
  zipkin:
      base-url: http://localhost:9411/
      sender:
          type: web
  sleuth:
      sampler:
          probability: 1


mybatis:
  type-aliases-package: com.newoxen.springcloud.tbms.admin.entity
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


pagehelper:
  helper-dialect: mysql

info:
  app.name: tbms-admindemo
  company.name: www.newoxen.com

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:12000/eureka/eureka
    instance:
      instance-id: admin-demo
      prefer-ip-address: true


feign:
  hystrix:
    enabled: true

oauth2-service-url: http://localhost:12999
security:
  oauth2:
    client:
      user-authorization-uri: ${oauth2-service-url}/oauth/authorize
      access-token-uri: ${oauth2-service-url}/oauth/token
    resource:
      user-info-uri: ${oauth2-service-url}/oauth/user
      prefer-token-info: false


xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    accessToken:
    executor:
      appname: xxl-job-executor-sample
      address:
      ip:
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30



logging:
  level:
    org.springframework.cloud.openfeign: debug