management:
  endpoints:
    web:
      exposure:
        include: 'routes'

server:
  port: 10088
  tomcat:
    max-threads: 200

spring:
  application:
    name: zuul-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false


zuul:
  sensitive-headers: Access-Control-Allow-Origin, Access-Control-Allow-Credentials, Cookie,Set-Cookie
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  #ignored-services: admin-service,admin-feign-service
  routes:
     oauth:
        path: /oauth/**
        url: http://127.0.0.1:12999/oauth
     admin-service:
        path: /api/admin/**
        url: http://127.0.0.1:12001/admin
     admin-feign-service:
        path: /api/admin-feign/**
        url: http://127.0.0.1:12002/admin-feign
  add-proxy-headers: true

info:
  app.name: tbms-gateway
  company.name: www.newoxen.com

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:12000/eureka/eureka
    instance:
      instance-id: gateway
      prefer-ip-address: true

feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

oauth2-service-url: http://localhost:12999
security:
  oauth2:
    client:
      user-authorization-uri: ${oauth2-service-url}/oauth/authorize
      access-token-uri: ${oauth2-service-url}/oauth/token
    resource:
      user-info-uri: ${oauth2-service-url}/oauth/user
      prefer-token-info: false

